### ISSUE TITLE
Highlight intra-line differences

### ISSUE THREAD

**Issue by normanr** [daveewart/colordiff#14]
Add some way to show intra-line differences.

There's already a perl script [1] in git contrib that does this, so merging the two may be easy (particularly because they're both GPL2 licence)

[1] https://github.com/git/git/blob/master/contrib/diff-highlight/diff-highlight

**Comment by daveewart** [comment]
This looks like an interesting idea: the "showing within-line differences" has been a common request for colordiff and it'd be good to do something with it.

I'm unclear on whether the best approach is to try to incorporate the diff-highlight logic into colordiff directly or whether to simply recommend use of diff-highlight as a 'post-processor' for existing coloured diff output.

**Comment by normanr** [comment]
I don't really mind, but it would be nice to re-use the logic from colordiff to detect pipes etc, and only active diff-highlight logic when color logic will also kick in.

Mainly because doing: `colordiff -u "$@" | diff-highlight` seems to break this detection, eg: `cat input.patch | colordiff -u "$@" | diff-highlight > output.patch`

**Comment by daveewart** [comment]
Forgot about this one, sorry: I'm not sure I should attempt to incorporate diff-highlight code here.  To be honest, diff-highlight does a much better job of showing intra-line differences for files with isolated one-line differences than colordiff does and so that seems to be a better solution!

**Comment by normanr** [comment]
Okay what about changing the request slightly then:  Provide a post-processor cmdline option, like `--postprocessor`.  If passed then instead of writing to STDOUT, the post-processor would be used in a pipe open `"| $post-processor"`, and output would be written to that pipe. (This logic would need to go after 'check if output is a file', and before 'disable output buffering'

This would allow the `(-f STDOUT)` check to work correctly, and still apply whatever post-processing would be required.

The alternative is writing a shell script like this:

```
#!/bin/bash
if [ -f /dev/stdout ]; then
  exec diff -u "$@"
else
  exec colordiff.pl -u "$@" | diff-highlight
fi
```

**Comment by daveewart** [comment]
My point was: for the requirement of "intra-line differences", use diff-highlight _instead_ of colordiff ... does that not make sense here?

**Comment by normanr** [comment]
Ahh, perhaps I understand the confusion now.  Colordiff and diff-highlight do different processing (color vs inter-line highlight).  I'd like both.  (Un)fortunately they both do 'is stdout a TTY' detection, so they can't be chained together easily.  It would be nice to be able to chain them without an extra shell script.
