### ISSUE TITLE
Highlighting for "Binary files differ" lines

### ISSUE THREAD

**Issue by janlarres** [daveewart/colordiff#15]
It would be useful to have a way to highlight diff's "Binary files x and y differ" lines. This would make it easier to distinguish those lines from normal file content (when using unified or context diffs), especially when quickly scanning a long diff.

**Comment by daveewart** [comment]
This seems pretty reasonable: I'll get something coded for this and committed shortly.  Thanks for the suggestion.

**Comment by daveewart** [comment]
This is included in https://github.com/daveewart/colordiff/commit/500e03953fc28897d7501aeb40734d1c7539aa06

**Comment by janlarres** [comment]
Great, thanks!
