### ISSUE TITLE
Output is empty when --difftype is specified and the specified type is not diffy

### ISSUE THREAD

**Issue by zmwangx** [daveewart/colordiff#22]
A very simple example: for 1.0.14 and 1.0.15,

```
diff file1 file2 | colordiff
```

works as expected, but

```
diff file1 file2 | colordiff --difftype=diff
```

produces empty output all the time. This worked back in 1.0.13.

**The offending commit seems to be 384eea619ec366f610d6c8070da724a7de69f1df** according to git-bisect.

I didn't read the code in detail so I'm not sure how `$lastline` is exactly useful, but my impression is that when `--difftype` is specified but the specified type is not `diffy`, then `@inputstream` would be empty and `$lastline` would be `undef` (although technically we assigned `$_` to `$lastline` in [line 315](https://github.com/daveewart/colordiff/commit/384eea619ec366f610d6c8070da724a7de69f1df#diff-7493820e9dfb24068e26675932262491R315), it doesn't really help since the condition `($diff_type eq 'diffy' and ($_ = <STDIN>))` results in an undefined `$_` when diff type is not `diffy`), so when we reach [the loop](https://github.com/daveewart/colordiff/commit/384eea619ec366f610d6c8070da724a7de69f1df#diff-7493820e9dfb24068e26675932262491R418)

``` perl
while (defined( $_ = @inputstream ? shift @inputstream : ($lastline and <STDIN>) )) {
```

the condition is immediately false although there's stuff in `<STDIN>` (which was later changed to `$inputhandle`).

Again, I didn't read the code in detail, so I won't try to submit a patch, which might break other things.

**Comment by daveewart** [comment]
Thanks for the bug report. The introduction of 'difftype' was most generally useful because some 'diffy' inputs not being recognisable and I suspect is not widely used otherwise: I agree this is a bug which should be addressed, but can I ask whether it is necessary, in your use case, to specify "--difftype=diff"? Can that simply not be dropped?

I'll try to figure out the best way to fix colordiff here: this was contributed code and my memory of it is fuzzy!

**Comment by zmwangx** [comment]
> ... whether it is necessary...

No it's not. `--difftype=diff` is completely useless here.

I found this bug because Prezto calls `colordiff` [in the following manner](https://github.com/sorin-ionescu/prezto/blob/a84ac5b0023d71c98bb28a68c550dc13f6c51945/modules/utility/functions/diff#L11):

``` zsh
command diff --unified "$@" | colordiff --difftype diffu
```

which exposes the bug in 1.0.14 and 1.0.15.

Now that should really be just

``` zsh
command colordiff --unified "$@"
```

and I have a PR there https://github.com/sorin-ionescu/prezto/pull/923 to address this.

Anyway, I think this is still a regression that should be addressed.

**Comment by daveewart** [comment]
I agree it's a regression and it will be addressed :-)

**Comment by zmwangx** [comment]
Great, thanks.

**Comment by Lekensteyn** [comment]
@daveewart Are you working on this or should I give it a shot?

**Comment by daveewart** [comment]
@Lekensteyn Hey, that would be great :-)  I was going to ask you about it anyway, because you contributed the original fix ;-)  Happy to accept a fix, certainly.
