### ISSUE TITLE
Provide current release tarball in "archive"?

### ISSUE THREAD

**Issue by lfam** [daveewart/colordiff#28]
Hi,

I'm working on the colordiff package for GNU Guix [0].

I noticed that the URL for the current release is structured differently from all the archived releases. For example, the current release is not available at :

```
http://colordiff.org/archive/colordiff-1.0.16.tar.gz
```

Would you consider making the current release tarball available under the "archive" directory so that packagers could rely on the single URL?

[0]
http://www.gnu.org/software/guix/

**Comment by daveewart** [comment]
Thanks for the request: I've put a copy of the current release (and its digital signature) in the 'archive' directory as well as in the base directory now.  Hope this is helpful, so setting this CLOSED.

**Comment by lfam** [comment]
Thank you!
