### ISSUE TITLE
Need of using /etc

### ISSUE THREAD

**Issue by eduardo4jesus** [daveewart/colordiff#29]
Hello folks,

I don't have sudo privileges on my workstation, so I have to use my own environment. I was willing to install colordiff by:
`make install INSTALL_DIR=$MY_TOOLS/bin MAN_DIR=$MY_TOOLS/man/man1
`

However, taking a look into the install commands with `make install -n` I saw that they use `/etc`:

`
if [ -f /etc/colordiffrc ]; then \
          mv -f /etc/colordiffrc \
            /etc/colordiffrc.old; \
        else \
          install -d /etc; \
        fi
cp colordiffrc /etc/colordiffrc
chown root.root /etc/colordiffrc
chmod 644 /etc/colordiffrc
`

Which environment variable should I load so that colordiff looks in the right path `$TOOLS/etc` instead of `/etc`?

Thanks in advance.

**Comment by daveewart** [comment]
You could trying setting ETC_DIR for this.

**Comment by eduardo4jesus** [comment]
I had considered that since we got this snippet code under `install:`

```
 23 install:                                                                        
 24     install -d ${DESTDIR}${INSTALL_DIR}                                         
 25     sed -e "s%/etc%${ETC_DIR}%g" colordiff.pl > \                               
 26       ${DESTDIR}${INSTALL_DIR}/colordiff                                        
 27     chmod +x ${DESTDIR}${INSTALL_DIR}/colordiff                                 
 28     if [ ! -f ${DESTDIR}${INSTALL_DIR}/cdiff ] ; then \                         
 29       install cdiff.sh ${DESTDIR}${INSTALL_DIR}/cdiff; \                        
 30     fi                                                                          
 31     install -Dm 644 colordiff.1 ${DESTDIR}${MAN_DIR}/colordiff.1                
 32     install -Dm 644 cdiff.1 ${DESTDIR}${MAN_DIR}/cdiff.1                        
 33     if [ -f ${DESTDIR}${ETC_DIR}/colordiffrc ]; then \                          
 34       mv -f ${DESTDIR}${ETC_DIR}/colordiffrc \                                  
 35         ${DESTDIR}${ETC_DIR}/colordiffrc.old; \                                 
 36     else \                                                                      
 37       install -d ${DESTDIR}${ETC_DIR}; \                                        
 38     fi                                                                          
 39     cp colordiffrc ${DESTDIR}${ETC_DIR}/colordiffrc                             
 40     -chown root.root ${DESTDIR}${ETC_DIR}/colordiffrc                           
 41     chmod 644 ${DESTDIR}${ETC_DIR}/colordiffrc
```

But then, I wondered how would `colordiff` "know" that it should looks for `colordiffrc` into `${DESTDIR}${ETC_DIR}` instead of `/etc`.

I mean, since I have installed programs using the prefix `$MY_TOOLS`, whenever I want to use one of these programs I have to activate my "environment" by sourcing a script that adds `$MY_TOOLS/bin` into `$PATH` and so on for the other system environment variables that I know.

Now, let's say I set `ETC_DIR` to path different of `/etc` like `$MY_TOOLS/etc`. Is there any environment variable that I should modify by adding `$ETC_DIR` in order to ensure `colordiff`is looking in the right place for `colordiffrc`?

**Comment by daveewart** [comment]
Lines 25 and 26 that you quote will replace '/etc' in the colordiff script itself with what you specify.  If this is a fixed path, it'll just work. Not sure how it'll behave if you want it to be an environment variable.  Perhaps just edit the live colordiff installed script directly in that case?

**Comment by daveewart** [comment]
I'm assuming there's nothing more needed here, so I'll close this issue in a few days if I don't here more.

**Comment by eduardo4jesus** [comment]
Hello @daveewart,

First, I want to thank you for clarifying which part of the script makes possible to use a different `ETC_DIR`. I couldn't actually try it because I couldn't get all requirements correctly installed, yet.

Apologies for taking so long for reply.

Best Regards.
