### ISSUE TITLE
intraline syntax highlighting fails when spanning newline char

### ISSUE THREAD

**Issue by isometric** [daveewart/colordiff#30]
colordiff currently improperly highlights changes when there's a newline char between the brackets such as in the case of

```
foo [-bar
bash-] derp
```

this is the default mode for wdiff

expected highlighting to be similar to wdiff -n

```
foo [-bar-]
[-bash-] derp
```

![screen shot 2016-08-13 at 11 07 38 am](https://cloud.githubusercontent.com/assets/1491297/17644959/eecb5b96-614b-11e6-8f37-163dcbc7ee6d.png)
![screen shot 2016-08-13 at 11 07 55 am](https://cloud.githubusercontent.com/assets/1491297/17644960/eecba290-614b-11e6-9a67-fb58b12fcd92.png)

**Comment by daveewart** [comment]
It's a noted limitation of colordiff that it will only add colour to wdiff output if the '-n' option is provided: this is documented on the man page and elsewhere.
