### ISSUE TITLE
colordiff-1.0.17 doesn't colorize anymore when piped through less

### ISSUE THREAD

**Issue by heirecka** [daveewart/colordiff#33]
Since updating to 1.0.17 colordiff doesn't colorize diffs anymore when piped through less. It even worked without passing -R/-r to less in the past, but now that doesn't help either. Nor does explicitly passing --color=yes to colordiff or setting color_patches=yes.
Version of less is 492.

**Comment by daveewart** [comment]
Oh, damn, I was particularly trying to avoid breaking that: it's one of the most common use cases.  Will fix this a.s.a.p.  Thanks for the report.

**Comment by daveewart** [comment]
One line fix ;-)

@heirecka  - please try 1.0.18 release or latest git and re-test.

**Comment by heirecka** [comment]
That was quick :-) Thank you!

**Comment by daveewart** [comment]
I was watching 'The Godfather Part III' and spotted your email: knew it was a very annoying bug that needed dealt with.  Now back to those nice Italian American gentlemen ... ;-)
