### ISSUE TITLE
manpage?

### ISSUE THREAD

**Issue by beelsr** [daveewart/colordiff#35]
There is no manpage in the repo.

make install dies on the lines:
> install -Dm 644 colordiff.1 ${DESTDIR}${MAN_DIR}/colordiff.1
> install -Dm 644 cdiff.1 ${DESTDIR}${MAN_DIR}/cdiff.1

**Comment by daveewart** [comment]
The manpage is generated from the XML files, so run 'make doc' first. Ideally there should be a dependency in the Makefile but not everyone has 'xmlto' installed and I didn't want unexpected breakage.  FWIW it's been like that for ~15 years and no-one else has ever mentioned it ;-)

**Comment by beelsr** [comment]
ahh, now i see that. 15 years huh?  :)

i'll just cp it from a centos server.  Installs fine from the epel repo, but the SLES repos don't have it (which is why I grabbed it from here).

**Comment by daveewart** [comment]
Nothing required here for now. Closing issue.
