### ISSUE TITLE
colordiff options not documented?

### ISSUE THREAD

**Issue by joaoe** [daveewart/colordiff#37]
Howdy.

I've installed `colordiff` normally through my distribution (ubuntu) and `man colordiff` does not document the `colordiff options` in a clear way. There are some references to command line options lost in the text.

Also, the config file format is not documented in the man page, so the user has to read through `/etc/colordiffrc`.

I tried `colordiff --help` but that is just interpreted as `diff --help`.

What I was looking at was options to customize the colors directly with arguments or point to some local config file. I realize now those use cases are not covered but I had to look through the code to find that out. But this is another issue.

Thank you.

**Comment by daveewart** [comment]
Hmm, I see what you mean.  Generally colordiff just feeds stuff through to diff, apart from a few colordiff-specific options.  I guess those could be clearer on the man page.  It's all in there somewhere.  I'll rewrite the preamble to make it clearer.

**Comment by adrian-gierakowski** [comment]
seems like the options are still not documented

**Comment by daveewart** [comment]
@adrian-gierakowski Yes, fair call, that was overlooked. Will do this alongside the other request you made. Thanks :-)

**Comment by daveewart** [comment]
Fixed as part of commit 11881104433da2b87d5bfa26ebd8a79d651c3774
