### ISSUE TITLE
Unified diff header is highlighted as changes

### ISSUE THREAD

**Issue by joaoe** [daveewart/colordiff#39]
Hi.

`$ diff -u <(echo 1) <(echo 2) | colordiff`

will interpret the lines like

```
#oldtext  # --- /dev/fd/63  2018-06-16 18:42:33.702021285 +0200
#newtext  # +++ /dev/fd/62  2018-06-16 18:42:33.702021285 +0200
#diffstuff# @@ -1 +1 @@
#oldtext  # -1
#newtext  # +2
```
The lines starting with 3 minus or pluses are all diff metadata or context. They are not removed nor added lines, so they should be styles with the `diffstuff` color.

Thank you.

**Comment by joaoe** [comment]
Ok, I tested with the version in `master` and it actually works correctly. Sorry for the noise.

**Comment by gedge** [comment]
has this returned?

**Comment by daveewart** [comment]
Just looking at this now.

**Comment by daveewart** [comment]
I believe fixed in latest master: please verify @gedge

**Comment by gedge** [comment]
@daveewart - looks fixed to me, many thanks

(next time, I'll submit a PR, promise!)
