### ISSUE TITLE
Missing option to control on/off ansi color code easily

### ISSUE THREAD

**Issue by ymattw** [daveewart/colordiff#4]
Hi,

I have a use case like this:

Use colordiff to view the diff

```
svn diff | colordiff
```

Apply the patch to another dir (arrow up and edit last command in my shell)

```
svn diff | colordiff | patch -p0 -d another-working-copy
```

Unfortunately this does not work since ansi color chars are piped out to `patch`.  I have to save the diff first:

```
svn diff | colordiff > my.patch
patch -p0 -d another-working-copy < my.patch
```

This is somehow inconvenient, could you provide a short option to on/off the ansi color code, just like what `grep` has (`grep --color=never,always,auto`)?

Thanks,<br>
Matt

**Comment by ymattw** [comment]
I didn't aware send pull request will create a new issue, will merge comment here to issue 5.

**Comment by daveewart** [comment]
ymattw: Apologies, I've completely missed the consequences of merging your patch: it's not easy to modify it to return colordiff to default behaviour for existing users.  I understand what you're trying to do here, so I'll re-open this issue and we can figure out the exact circumstances which require changes.  Sorry for the confusion.

**Comment by daveewart** [comment]
What is required is that

```
svn diff | colordiff
```

provides colour.  Also, that

```
svn diff | colordiff | patch -p0 -d another-working-copy
```

does not put colour in the output pipe.  But, equally, to retain existing widespread behaviour

```
svn diff | colordiff | less -R
```

should show the colours in the less output.  The difficulty is in distinguishing the latter two cases because they both put colours out on the pipe: I suspect a One Size Fits All approach won't work.

**Comment by ymattw** [comment]
Seems I did not refer this issue number with the correct format (must be "#4") in my new pull request... and it created issue 6, sorry about that.

**Comment by daveewart** [comment]
Closing this issue in favour of #6
