### ISSUE TITLE
Support for true color

### ISSUE THREAD

**Issue by StephenWall** [daveewart/colordiff#40]
Would be nice to have support for true color in `.colordiffrc`.
The escape sequence to set the foreground color is `<ESC>[38;2;r;g;bm` where `r`, `g`, and `b` are integers 0-255.  Substitute `38` with `48` to set background color.
It'd also be nice to be able to set the bold attribute with these.
A simple way to handle both would be to scan the color value for semi-colons (`;`), and if present, assume it's everything that goes between the `[` and `m` in the above sequence.

**Comment by daveewart** [comment]
Seems like a good idea: I'll code something up to support it, need to figure out why my terminals-of-choice don't seem to support the escape sequences first!

**Comment by daveewart** [comment]
Just wondering what the best way to specify these in the config file might be: at present, using the colour names ('magenta' etc.) works for plain 16 colours, and a number from 0 to 255 works for 256 colours, i.e.

````
oldtext=red
newtext=40
````
Is your intention to use something like this?
````
oldtext=0;38;2;140;20;20
newtext=1;38;2;40;255;40
````
for example?

**Comment by StephenWall** [comment]
I have a patch in locally that accepts exactly that form.  I suspect some people would want a text string for attributes (bold, reverse, etc) that you could list together with a color, but that's far beyond anything I'd care about.
```
--- colordiff.pl.orig   2019-04-15 18:39:51 UTC
+++ colordiff.pl
@@ -226,7 +226,10 @@ foreach $config_file (@config_files) {
             if (($value eq 'normal') || ($value eq 'none')) {
                 $value = 'off';
             }
-            if ($value =~ m/[0-9]+/ && $value >= 0 && $value <= 255) {
+            if ( $value =~ m/^[0-9]+(;[0-9]+)+$/ ) {
+                $colourval = "\033[0;${value}m";
+            }
+            elsif ($value =~ m/[0-9]+/ && $value >= 0 && $value <= 255) {
                 # Numeric color
                 if( $value < 8 ) {
                     $colourval = "\033[0;3${value}m";
```

**Comment by daveewart** [comment]
Stephen: I've just pushed a patch based on your patch above and included some error-checking. Does it behave as you expect with config options you indicate?  Non-bold, bold & 24-bit colour spec should all be supported as per my testing.

https://github.com/daveewart/colordiff/commit/fb2e2e8e1825160d6b1ad446c518488389d9d534

**Comment by StephenWall** [comment]
It works, though the requirement for 0 or 1 at the beginning will likely cause some confusion, and hard coding the 38 prevents setting background color.  Could I suggest this?
```
             if (( $value =~ m/^([0-9];)*([34]8);2;([0-9]+);([0-9]+);([0-9]+)$/) &&
                    ($3 >= 0) && ($3 <= 255) &&
                    ($4 >= 0) && ($4 <= 255) &&
                    ($5 >= 0) && ($5 <= 255)
                    ) {
                $colourval = "\033[$1$2;2;$3;$4;$5m";
```
This gives the flexibility of adding any or none of the attributes at the beginning, and specifying a background color instead of a foreground color.  Though I wouldn't be heartbroken if you didn't support background colors... :)

**Comment by daveewart** [comment]
Stephen: Apologies for leaving this one for so long, I've incorporated the above now. Does it now behave as you'd expect?

**Comment by daveewart** [comment]
I think this is now included in base code, closing this Issue.

**Comment by StephenWall** [comment]
Sorry, I guess I'm not good about keeping up on github... :)  I'll try to double check this this week.
