### ISSUE TITLE
Result of colordiff to PDF or image?

### ISSUE THREAD

**Issue by rccclr** [daveewart/colordiff#45]
Hello
How obtain a pdf/img result of colordiff?
The result is perfect in screen, but for export ?
Many thanks

**Comment by daveewart** [comment]
Don’t really understand what you’re asking for here: an option to colordiff which takes a screenshot?! I think better suited for another utility. Unless you mean something else ... ?

**Comment by rccclr** [comment]
Sorry for the question, with this is valid for me:

diff $i ../original/$i | colordiff | aha > ../diff/$i.html
convert ../diff/$i.html ../diff/$i.png

Many thanks

**Comment by daveewart** [comment]
Ah, I see what you mean. Looks like you have a good solution: use a pipeline of tools :-)
