### ISSUE TITLE
install -D option not available on MacOS

### ISSUE THREAD

**Issue by matthiasdiener** [daveewart/colordiff#46]
Colordiff fails to install on MacOS since its `install` program does not support the `-D` option:

```
$ install -Dm
install: illegal option -- D
```

**Comment by daveewart** [comment]
Apologies for missing this one. I don't have access to MacOS to test, but does this just need
````
install -Dm 644 TARGETDIR/file
````
replaced with
````
mkdir TARGETDIR
install -m 644 TARGETDIR/file
````
or is there more to it than that?

**Comment by matthiasdiener** [comment]
> Apologies for missing this one. I don't have access to MacOS to test, but does this just need
> 
> ```
> install -Dm 644 TARGETDIR/file
> ```
> 
> replaced with
> 
> ```
> mkdir TARGETDIR
> install -m 644 TARGETDIR/file
> ```
> 
> or is there more to it than that?

I think that would work. You could probably also use 

```
install -d TARGETDIR
install -m 644 TARGETDIR/file
```

**Comment by daveewart** [comment]
https://github.com/daveewart/colordiff/commit/8ce5f432716393b1c80aa6576a42ee1b70a07cd5 Uploaded just now. Does this work for you Matthias?

**Comment by matthiasdiener** [comment]
> [8ce5f43](https://github.com/daveewart/colordiff/commit/8ce5f432716393b1c80aa6576a42ee1b70a07cd5) Uploaded just now. Does this work for you Matthias?

Yes, this works. Thank you!
