### ISSUE TITLE
colordiff -y not outputting color on CentOS7

### ISSUE THREAD

**Issue by Ajhad1** [daveewart/colordiff#47]
> I recently posted [here](https://superuser.com/questions/1576965/colordiff-y-does-not-color-output-in-centos7) of what I thought was user error while using `colordiff` but after some troubleshooting, I believe that it may be a bug. Below is a copy of my issue. Looking for some help, please.

For the life of me, I cannot get `colordiff` to output color to the terminal. I feel like I am missing something simple.

[Example of no color output][1]

Environment:

 - `cat /etc/centos-release` = CentOS Linux release 7.5.1804 (Core)
 - `colordiff --version` = diff (GNU diffutils) 3.3
 - `sudo yum info diffutils` = Version     : 3.3 | Release     : 5.el7
 - `sudo yum info colordiff` = Version     : 1.0.13 | Release     : 2.el7
 - Terminal = PuTTY Release 0.74
 - OS = Microsoft Windows 10 Home | Version	10.0.19041 Build 19041

The specific command I am trying:
 - `\colordiff -y --left-column /opt/projects/openidm/subscribers/conf/authentication.json /opt/projects/git/subscribers/conf/authentication.json`

Commands I have tried but will not output color:
 - `\colordiff -y --left-column <File-1> <File-2>`
 - `\colordiff -y --left-column --difftype=diffy <File-1> <File-2>`

Commands that will output color in the terminal for all files:
 - `\colordiff <File-1> <File-2>`
 - `\colordiff -y --ignore-trailing-space <File-1> <File-2>`
 - `\colordiff -y --ignore-trailing-space --suppress-common-lines <File-1> <File-2>`
 - `\colordiff -y --left-column --ignore-trailing-space --suppress-common-lines <File-1> <File-2>`

Commands that output color depending on the type of "diffs" in the files:
 - `\colordiff -y --left-column --suppress-common-lines <File-1> <File-2>`
 - `\colordiff -y --left-column --suppress-common-lines --difftype=diffy <File-1> <File-2>`
 - `\colordiff -y --suppress-common-lines <File-1> <File-2>`
 - `\colordiff -y --suppress-common-lines --difftype=diffy <File-1> <File-2>`
 - `\colordiff -y <File-1> <File-2>`
 - `\colordiff -y --difftype=diffy <File-1> <File-2>`
 - `\diff -y  <File-1> <File-2> | \colordiff`
 - `\diff -y  <File-1> <File-2> | \colordiff --difftype=diffy`

Note: I have preceded most commands with a `\` to make sure no aliases are involved.

Update: After trying multiple files for comparison, it turns out that the original files I was comparing had a trailing space that was causing an issue. That said, the issue still requires that I add `--suppress-common-lines` to my original command, even though in my case, that only removes 2 lines from the output.

[Only working edge case for -y --left-column][2]

  [1]: https://i.stack.imgur.com/0J1C3.png
  [2]: https://i.stack.imgur.com/7nHtp.png

**Comment by daveewart** [comment]
If you are really using colordiff 1.0.13 then that’s ancient. Try with most recent version. In particular, version 1.0.14 (released 2015) introduced a lot of extra support for side-by-side diffs.

**Comment by Ajhad1** [comment]
Thank you for responding. 

CentOS 7 EPEL only has version 1.0.13 but I have submitted a bug report to update the release to at least 1.0.14 here 
https://bugzilla.redhat.com/show_bug.cgi?id=1868695

I am not sure about their process but I have linked that report to this one so they can see your comment.

**Comment by daveewart** [comment]
CentOS 7 is a current supported release, it really should have a more recent version than 1.0.13 which was released in 2012! I’m assuming that’s all it has because when CentOS 7.0 was released in 2014 that was the current version: perhaps no-one is maintaining the package there any more? There have been a number of releases since then, see https://www.colordiff.org/archive/

Anyway a new version will solve your issue, so I’ll close this one. Good luck :-)

**Comment by Ajhad1** [comment]
The version included in CentOS 7 EPEL has been updated to colordiff 1.0.19
https://bugzilla.redhat.com/show_bug.cgi?id=1868695#c14

Thank you for responding.

**Comment by richardfearn** [comment]
Also updated in EPEL 6: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-f86c8b7635

**Comment by alexcanepa** [comment]
I get the same issue with `colordiff 1.0.19` on both Ubuntu and MacOS, where the output is identical to that of `diff`

**Comment by daveewart** [comment]
> I get the same issue with `colordiff 1.0.19` on both Ubuntu and MacOS, where the output is identical to that of `diff`

Hi @alexcanepa - this is an old issue which has been closed. You haven't provided much detail of the problem you are seeing, please could you open a new issue with as much detail as possible about your setup and I'll take a look?
