### ISSUE TITLE
add command line flag to disable banner

### ISSUE THREAD

**Issue by adrian-gierakowski** [daveewart/colordiff#57]
seems like it's only possible to disable the banner via a config file

**Comment by daveewart** [comment]
@adrian-gierakowski Thanks for reporting, will get that included.

**Comment by daveewart** [comment]
Commit 019d9140b4a402a0517cd28eb1f35f29f97d0b9c now includes options --banner and --nobanner, to over-ride defaults and config files.

**Comment by adrian-gierakowski** [comment]
Very nice sir, thank you!
